### ISSUE TITLE
Similar project but faster

### ISSUE THREAD

**Issue by 0uep** [unix-world/smartgo#1]
Hi Radu,

I have just started a new project BaseXX:
https://github.com/teal-finance/BaseXX

This is very similar to what you did. :smile:

I have selected another Base58 project that is faster than the one you choose as original work. You can run the benchmark on your computer, [BaseXX](https://github.com/teal-finance/BaseXX) is about five times faster:

	go test -run=NO -bench=. -benchmem github.com/teal-finance/BaseXX/base92
	  
	goos: linux
	goarch: amd64
	pkg: github.com/teal-finance/BaseXX/base92
	cpu: AMD Ryzen 9 3900X 12-Core Processor            
	BenchmarkEncode-24                       1000000              1944 ns/op              96 B/op          2 allocs/op
	BenchmarkEncodeSmartgoBase92-24           135556              8722 ns/op            1377 B/op         78 allocs/op
	BenchmarkDecode-24                       1794903               673.5 ns/op           122 B/op          2 allocs/op
	BenchmarkDecodeSmartgoBase92-24           339506              3496 ns/op             232 B/op          8 allocs/op
	PASS
	ok      github.com/teal-finance/BaseXX/base92   6.404s

Have fun :grinning:

**Comment by unix-world** [comment]
Hi,
I will look over your project. Looks interesting.

The BaseXX project is also portable in javascript and php so my first purpose is to have that logic.
Second, every piece of code inside smartgo is threadsafe in multi-threading usage (except webview2 ... which is includded there for another purpose).

Thus in multi-threading I was focusing on not having "concurrency issues".
Perhaps yours is the same, but I did not yet look too deep.

**Comment by unix-world** [comment]
Hi [0uep](https://github.com/0uep)

Actually you did a very wrong measure ...
I am not sure how did you get those results :-)
But let's make a simple test.

Simple test: Encode / Decode GPL v3
https://raw.githubusercontent.com/Illumina/licenses/master/gpl-3.0.txt

smartgo/base92 (my project):
ENCODE: 888.378397ms ; DECODE: 191.787475ms

Your project:
ENCODE: 1.082452169s ; DECODE: 254.817341ms

```golang
// my version (FASTER) ; ENCODE: 888.378397ms ; DECODE: 191.787475ms
package main

import (
	"log"
	"time"

	smart "github.com/unix-world/smartgo"

	b92 "github.com/unix-world/smartgo/base92"

)

func main() {

	var timerStart time.Time

	txt, _ := smart.SafePathFileRead("gpl-3.0.txt", false)

	timerStart = time.Now()
	etxt := b92.Encode([]byte(txt))
	durationEnc := time.Since(timerStart)

	timerStart = time.Now()
	dtxt, _ := b92.Decode(etxt)
	durationDec := time.Since(timerStart)

	log.Println(dtxt, etxt, durationEnc, durationDec)

} //END FUNCTION
```

```golang
// your version (SLOWER) ; ENCODE: 1.082452169s ; DECODE: 254.817341ms
package main

import (
	"log"
	"time"

	smart "github.com/unix-world/smartgo"

	b92 "github.com/teal-finance/BaseXX/base92"

)

func main() {

	var timerStart time.Time

	txt, _ := smart.SafePathFileRead("gpl-3.0.txt", false)

	timerStart = time.Now()
	etxt := b92.Encode([]byte(txt))
	durationEnc := time.Since(timerStart)

	timerStart = time.Now()
	dtxt, _ := b92.Decode(etxt)
	durationDec := time.Since(timerStart)

	log.Println(dtxt, etxt, durationEnc, durationDec)

} //END FUNCTION
```

# Please notice, I only measured the encoding and decoding time.
As you can see the tests are identical ...

**Comment by unix-world** [comment]
Just download the https://raw.githubusercontent.com/Illumina/licenses/master/gpl-3.0.txt and put in the same folder as my tests and sww how results are ;-)

**Comment by unix-world** [comment]
Looking a bit over your code I also noticed some possible multi-concurrency issues which have to be also tested a lot to be sure it dows not panic under heavy loads by accessing same areas simultaneous

**Comment by unix-world** [comment]
Be sure you compile the files using go build if you want a real test. Benchmarking with go as you did measures something different. I measured exactly the encode and decode time not Go benchmark times which are mostly tricky ...

**Comment by 0uep** [comment]
Dear Radu

Thank you for your involvement and your useful replies.
You are right, my implementation is not faster.

I have been inspired by your Go samples and have also coded a bench command:
https://github.com/teal-finance/BaseXX/blob/main/examples/bench/main.go

You can test it right now:

    go run github.com/teal-finance/BaseXX/examples/bench -f gpl-3.0.txt

About the multi-concurrency issues, I think read-only data do not need a mutex in Go. You may remove some mutexes in your code…

I will update soon the README of BaseXX to say your project as similar performance with larger samples. ;-)

I think our two projects are too slow compared to https://github.com/mtraver/base91 results. Thus, on the new project https://github.com/teal-finance/incorruptible, I have decided to switch to https://github.com/mtraver/base91 because https://github.com/teal-finance/BaseXX is too slow.

PS: congratulations for your awesome projects, I have been impressed by http://demo.unix-world.org/smart-framework/?/page/samples.testunit/tab/0/CamelCase/Test/

**Comment by unix-world** [comment]
To be honest, concurrent map read still requires a read mutex in high concurrency.
Read/Write requires a RW Mutex. At least this is what I found out ... based on some experience in real environments.

**Comment by 0uep** [comment]
Thank you for sharing your experience about concurrent map read/write.

I quote your previous message:

> Looking a bit over your code I also noticed some possible multi-concurrency issues which have to be also tested a lot to be sure it does not panic under heavy loads by accessing same areas simultaneous

I have not found any mutex in this code:
https://github.com/unix-world/smartgo/blob/master/baseconv/baseconv.go

Neither in standard `"encoding/base64"`:
https://github.com/golang/go/blob/master/src/encoding/base64/base64.go

I think there is no concurrent issue in our both BaseN-related projects.
